name: CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
    - uses: actions/checkout@master
    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt-get -y install gcc libdbus-1-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav libgtk-3-dev libatk1.0-dev libcogl-pango-dev libssl-dev libcairo2-dev libgstreamer-plugins-bad1.0-dev

    - name: Build
      run: cargo build --verbose --no-default-features --features gtk_3_18
